### ISSUE TITLE
v0.0.4 release outputs v0.0.3

### ISSUE THREAD

**Issue by colinrymer** [hone/mruby-cli#27]
The **v0.0.4** release outputs `mruby-cli version 0.0.3` when running `mruby-cli -v`.

**Comment by colinrymer** [comment]
To be more specific, this is for the https://github.com/hone/mruby-cli/releases/download/v0.0.4/mruby-cli-0.0.4-x86_64-apple-darwin14.tgz release.

**Comment by hone** [comment]
Thanks for reporting this. I forgot to recompile before I packaged everything up. I've updated the release notes artifacts, so the new binary should be fixed!
