### ISSUE TITLE
Can't build windows binaries

### ISSUE THREAD

**Issue by kjunichi** [hone/mruby-cli#31]
Hi, mruby-cli is great!

But, I've got following errors.

```
CC    build/mrbgems/mruby-io/src/io.c -> build/x86_64-w64-mingw32/mrbgems/mruby-io/src/io.o
/home/mruby/code/mruby/build/mrbgems/mruby-io/src/io.c: In function 'mrb_cloexec_pipe':
/home/mruby/code/mruby/build/mrbgems/mruby-io/src/io.c:156:3: error: implicit declaration of function 'pipe' [-Werror=implicit-function-declaration]
   ret = pipe(fildes);
   ^
cc1: some warnings being treated as errors
```

it seems that mingw-w64 compiler is more strict for declaration check.

I found work around :

``` rb
# spec.add_dependency 'mruby-mtest', :mgem => 'mruby-mtest'
```

but, this is wrong.
we have no test.

thanks.

**Comment by zzak** [comment]
@kjunichi Thanks for your report! I will look into it and see if I can fix it upstream.

/cc @tsahara

**Comment by tsahara** [comment]
pipe(2) requires `<unistd.h>` [on POSIX platforms](http://pubs.opengroup.org/onlinepubs/009695399/functions/pipe.html).  What is needed on mingw32?

**Comment by kjunichi** [comment]
I'm not familiar with Mingw32,but following is my research.

io.h had _pipe function.

This page says that 

``` c
#define pipe(fds) _pipe(fds, 5000, _O_BINARY) 
/* replace 5000 with whatever buffer size you want to use */
```
- http://mingw.5.n7.nabble.com/How-does-mingw-support-pipe-td8714.html

Does this help up?

thanks.

**Comment by tsahara** [comment]
Thank you!  I tried `_pipe` macro but it is not a drop-in replacement of POSIX pipe(2) as written in the page, so I have merged https://github.com/iij/mruby-io/pull/53 to remove pipe support on Windows platforms.  Could you try updated mruby-io?  `docker-compose run compile` runs without error for me.

**Comment by kjunichi** [comment]
Thank you very much!

It works fine on both 32bit and 64bit windows platform.

**Comment by zzak** [comment]
Glad to see this resolved, thank you for your efforts!

お疲れ様でした！！
