### ISSUE TITLE
"docker-compose run compile" doesn't work on Windows 10

### ISSUE THREAD

**Issue by bamchoh** [hone/mruby-cli#42]
When I execute `docker-compose run compile`, it's error:

```
[31mERROR
Please pass the -d flag when using `docker-compose run`.
```

Is my execution way wrong?

Please see the below GIF file for the details:

![aaa](https://cloud.githubusercontent.com/assets/1514726/14432142/c5ecc944-0043-11e6-8243-3bd435714db2.gif)

My environment:
- docker version is 1.10.2, build c3959b1
- mruby-cli version is 0.0.4

**Comment by zzak** [comment]
What happens when you try `docker-compose run -d compile`?

**Comment by bamchoh** [comment]
It succeeded. Thank you.
![image](https://cloud.githubusercontent.com/assets/1514726/14468677/b7146930-011b-11e6-8f9e-04870f3010d3.png)

**Comment by toch** [comment]
It is a [known limitation](https://github.com/docker/compose/blob/master/compose/cli/main.py#L678) of docker in the Window shell.

I've just updated the README file to add the flag `-d` when running on windows. cf #46

I close this issue.
