### ISSUE TITLE
Can't compile with mruby-yaml

### ISSUE THREAD

**Issue by kyanny** [hone/mruby-cli#50]
Hi, I can't compile project with `mruby-yaml` mgem.
It is appreciate if you could point out what I am doing wrong. Thank you.

Current mruby (master HEAD; 6498970d81f6d0577a3eca77a9bf61040fb87e4c) can compile with `mruby-yaml`.
https://gist.github.com/kyanny/dbb2712f623ab529af2b01554a9ffe3b

But when I create new project by latest mruby-cli (v0.0.4) then compile project with `mruby-yaml`, compile fails.
https://gist.github.com/kyanny/a98124a54d9d8346c7e4f05b5690e9b5

Same happens with mruby-cli master HEAD; 287d1564a48eaa35e29590588d6e9f0dd9545d63
https://gist.github.com/kyanny/f10ec0163a85a8e96a530d8c044121d0

My system information is here.
https://gist.github.com/kyanny/6780f40f82a4a0e417ecfc11bf11de48

**Comment by toch** [comment]
@kyanny thanks for the report. it seems it doesn't find one of the include file.

is the mruby-yaml mgem [that one](https://github.com/AndrewBelt/mruby-yaml)?

**Comment by kyanny** [comment]
@toch 
Yes, I think that one.

**Comment by zzak** [comment]
Can you try using @hone's fork? https://github.com/hone/mruby-yaml

**Comment by kyanny** [comment]
@zzak 
Ah, `hone/mruby-yaml` works fine!

**Comment by kyanny** [comment]
💭  I wonder why https://github.com/mruby/mgem-list/blob/master/mruby-yaml.gem is not updated..

**Comment by kyanny** [comment]
Anyway, I will close this issue since the original problem has been solved.
Thank you @toch and @zzak for your help!

**Comment by hone** [comment]
Sorry about that, my [PR was never merged](https://github.com/AndrewBelt/mruby-yaml/pull/7).

**Comment by kyanny** [comment]
Never mind, now mgem-list refers hone/mruby-yaml! https://github.com/mruby/mgem-list/pull/192 (and I can compile mruby-cli project with `mgem: 'mruby-yaml'`) 😄

**Comment by toch** [comment]
Awesome, Thanks @kyanny !
